version: "3.8"

services:
  db_mysql:
    image: mysql:8
    env_file:
      - .env-mysql
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "5555:3306"
    restart: on-failure
volumes:
  mysql_data: